# Generated by Django 3.0.5 on 2020-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Destrication', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Call', models.CharField(max_length=20)),
                ('Maps_Link', models.URLField(max_length=250)),
            ],
        ),
    ]
