# Generated by Django 3.0.5 on 2020-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Name', models.CharField(max_length=50)),
                ('Name_Type', models.CharField(choices=[('Docker', 'Docker'), ('AspNetCore', 'AspNetCore'), ('Python', 'Python')], max_length=15)),
                ('Type_Filter', models.CharField(choices=[('filter-docker', 'filter-docker'), ('filter-docker', 'filter-docker'), ('filter-docker', 'filter-docker')], max_length=15)),
                ('Blog_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
