# Generated by Django 3.0.5 on 2020-12-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Type_Filter',
            field=models.CharField(choices=[('filter-docker', 'filter-docker'), ('filter-asp', 'filter-asp'), ('filter-python', 'filter-python')], max_length=15),
        ),
    ]
