# Generated by Django 3.0.5 on 2020-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201227_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_img',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
