# Generated by Django 3.0.5 on 2020-12-27 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201227_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=datetime.datetime(2020, 12, 27, 13, 2, 16, 510378, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
