# Generated by Django 3.0.5 on 2021-01-01 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 1, 44, 54, 649185)),
        ),
    ]
